/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 laptop.gltf --transform
Author: Blue Lantern (https://sketchfab.com/genoris2)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-laptop-8330c89e8431451db3aa9d15c5836ddf
Title: CyberPunk Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Laptop(props) {
  const { nodes, materials } = useGLTF('../laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['Material.025']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.027']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.029']} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['Material.019']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['Material.020']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['Material.021']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials['Material.033']} position={[0, 0.096, -0.728]} rotation={[-1.735, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/laptop-transformed.glb')
